import os
import logging

import requests
import subprocess
import time

logger = logging.getLogger(__name__)

OLLAMA_PROCESS = None

def ensure_ollama_server():
    """Check if Ollama server is running; if not, start it."""
    global OLLAMA_PROCESS
    # Quick ping to check if it’s already running
    try:
        requests.get("http://localhost:11434/api/tags", timeout=5)
        return  # already up
    except Exception:
        pass

    env = os.environ.copy()
    env["OLLAMA_NUM_GPU_LAYERS"] = "999"

    # Start Ollama server
    OLLAMA_PROCESS = subprocess.Popen(["ollama", "serve"], env=env)

    # Give it a moment to start
    for _ in range(20):
        try:
            requests.get("http://localhost:11434/v1/models", timeout=5)
            return
        except Exception:
            time.sleep(0.5)

    raise RuntimeError("Ollama server did not start.")

def stop_ollama_server():
    """Stop the Ollama server if it was started"""
    global OLLAMA_PROCESS

    if OLLAMA_PROCESS is None:
        logger.debug("No stored server process to stop.")
        return

    OLLAMA_PROCESS.terminate()
    try:
        OLLAMA_PROCESS.wait(timeout=5)
        logger.info("Ollama server terminated cleanly.")
    except subprocess.TimeoutExpired:
        OLLAMA_PROCESS.kill()
        logger.warning("Ollama server force-killed.")

    OLLAMA_PROCESS = None

def map_labels_to_descriptiveTopics_imgs(topics, img_path, llm_labels):
    """
    Maps topic IDs to their descriptive labels and associated image paths.

    Args:
        topics (list): List of topic IDs for each document/image.
        img_path (list): List of image paths corresponding to each document/image.
        llm_labels (list): List of descriptive labels generated by llm for each topic ID.

    Returns: dict: Mapping of topic IDs to their descriptive labels and associated image paths.
    """
    # Initialize: topic_id → {"llm_label": ..., "img_paths": [...]}
    topic_map = {}

    # Unique topic IDs present in your data (including -1)
    unique_topic_ids = sorted(set(topics))

    for topic_id in unique_topic_ids:
        topic_map[topic_id] = {
            "llm_label": llm_labels[topic_id],   # generated earlier
            "img_paths": [],
            "count": 0
        }

    # Fill in image paths
    for topic_id, path in zip(topics, img_path):
        topic_map[topic_id]["img_paths"].append(path)
        topic_map[topic_id]["count"] += 1

    return topic_map